export default {
  tastings: [
    {
      id: "cbc787a0-ffaf-11e8-8eb2-f2801f1b9fd1",
      name: "Yacochuya",
      modified: "2019-01-03T00:00:00.000Z",
      producer: "The Etcharts",
      varietal: "Malbec",
      vintage: "2007",
      country: "Argentina",
      region: "Salta's Cafayene valley",
      sigth_clarity: "Clear",
      sigth_concentration: "Pale",
      sigth_color_white: "Yellow",
      sigth_color_red: "Ruby",
      sigth_rim: true,
      sigth_extract: "Medium",
      sigth_tearing: "Ligth",
      sigth_gas: false,
      nose_condition: "TCA",
      nose_intensity: "Delicate",
      nose_age: "Youthful",
      nose_fruit_white: "Citrus, Apple/Pear",
      nose_fruit_red: "Red, Blue",
      nose_nonfruit: "Floral",
      nose_earth: "Compost, Mushrroms",
      nose_mineral: "Wet Stone, Limestone",
      nose_wood_age: "Old",
      nose_wood_size: "Small",
      nose_wood_origin: "French",
      palate_sweetness: "Bone-dry",
      palate_fruit_white: "Tropical, Apple/Pear",
      palate_fruit_red: "Red, Black",
      palate_nonfruit: "Vegetable",
      palate_earth: "Mushrooms",
      palate_mineral: "Chalk, Flint",
      palate_wood_age: "Old",
      palate_wood_size: "Small",
      palate_wood_origin: "American",
      palate_tannins: "Med +",
      palate_acidity: "Low",
      palate_alcohol: "High",
      palate_complexity: "Med-",
      palate_length: "Short",
      palate_body: "Med+",
      palate_texture: "Creamy",
      conclusion_pairing: "Pichana with fresh rugula",
      conclusion_comments:
        "Spectacular wine from Salta. Deep red. Complex, red and ripe fruits.",
      score: 75,
    },
    {
      id: "cbc787a0-ffaf-11e8-8eb2-f2801f1b9fd1",
      name: "Yacochuya",
      modified: "2019-01-03T00:00:00.000Z",
      producer: "The Etcharts",
      varietal: "Malbec",
      vintage: "2007",
      country: "Argentina",
      region: "Salta's Cafayene valley",
      sigth_clarity: "Clear",
      sigth_concentration: "Pale",
      sigth_color_white: "Yellow",
      sigth_color_red: "Ruby",
      sigth_rim: true,
      sigth_extract: "Medium",
      sigth_tearing: "Ligth",
      sigth_gas: false,
      nose_condition: "TCA",
      nose_intensity: "Delicate",
      nose_age: "Youthful",
      nose_fruit_white: "Citrus, Apple/Pear",
      nose_fruit_red: "Red, Blue",
      nose_nonfruit: "Floral",
      nose_earth: "Compost, Mushrroms",
      nose_mineral: "Wet Stone, Limestone",
      nose_wood_age: "Old",
      nose_wood_size: "Small",
      nose_wood_origin: "French",
      palate_sweetness: "Bone-dry",
      palate_fruit_white: "Tropical, Apple/Pear",
      palate_fruit_red: "Red, Black",
      palate_nonfruit: "Vegetable",
      palate_earth: "Mushrooms",
      palate_mineral: "Chalk, Flint",
      palate_wood_age: "Old",
      palate_wood_size: "Small",
      palate_wood_origin: "American",
      palate_tannins: "Med +",
      palate_acidity: "Low",
      palate_alcohol: "High",
      palate_complexity: "Med-",
      palate_length: "Short",
      palate_body: "Med+",
      palate_texture: "Creamy",
      conclusion_pairing: "Pichana with fresh rugula",
      conclusion_comments:
        "Spectacular wine from Salta. Deep red. Complex, red and ripe fruits.",
      score: 100,
    },
  ],
};
